feat: Update Zigbee2MQTT to version 1.39.0-1 and add Zigbee directory

diff --git a/.github/workflows/mono_repo_publish.yml b/.github/workflows/mono_repo_publish.yml
--- a/.github/workflows/mono_repo_publish.yml
+++ b/.github/workflows/mono_repo_publish.yml
@@ -4,366 +4,39 @@ on:
     branches: master
 
 jobs:
-    push-zb01:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB01
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb01/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
+  push-job:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        zb: [zb01, zb02, zb03, zb04, zb05, zb06, zb07, zb08, zb09, zb10, zigbee2mqtt-edge, zigbee2mqtt-proxy, common]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    push-zb02:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB02
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb02/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
-          
-    push-zb03:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB03
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb03/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
-                      
-    push-zb04:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB04
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb04/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
+      - name: Fetch all branches
+        run: git fetch --all
 
-    push-zb05:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB05
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb05/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
+      - name: Reset to remote main
+        run: git reset --hard origin/main
 
-    push-zb06:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB06
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb06/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
+      - name: Push ${{ matrix.zb }}
+        uses: dmnemec/copy_file_to_another_repo_action@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+        with:
+          source_file: "${{ matrix.zb }}/"
+          destination_repo: 'racksync/hass-addons-suite'
+          destination_folder: 'multipoint-zigbee/'
+          user_email: 'devops@racksync.com'
+          user_name: 'racksync'
+          commit_message: '${{ matrix.zb }} has been updated from legacy codebase'
 
-    push-zb07:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB07
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb07/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
+      - name: Pull and rebase latest changes
+        run: |
+          git pull --rebase origin main || { echo "Rebase failed, aborting..."; git rebase --abort; exit 1; }
 
-    push-zb08:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB08
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb08/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
-
-    push-zb09:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB09
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb09/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
-
-    push-zb10:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push ZB10
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zb10/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
-
-    push-zigbee2mqtt-edge:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push zigbee2mqtt-edge
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zigbee2mqtt-edge/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
-
-    push-zigbee2mqtt-proxy:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push zigbee2mqtt-proxy
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "zigbee2mqtt-proxy/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
-
-    push-common:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-          - name: Fetch all branches
-            run: git fetch --all
-          - name: Reset to remote main
-            run: git reset --hard origin/main
-          - name: Push Common
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
-            with:
-                source_file: "common/"
-                destination_repo: 'racksync/hass-addons-suite'
-                destination_folder: 'multipoint-zigbee/'
-                user_email: 'devops@racksync.com'
-                user_name: 'racksync'
-                commit_message: 'multi-point zigbee has been updated from legacy codebase'
-          - name: Pull latest changes
-            run: git pull origin main
-          - name: Push changes with retry
-            run: |
-              for i in {1..5}; do
-                git push -u origin HEAD:main && break || sleep 15
-              done
+      - name: Push changes with retry
+        run: |
+          for i in {1..5}; do
+            git pull --rebase origin main && git push -u origin HEAD:main && break || { echo "Push failed, retrying in 15 seconds..."; sleep 15; }
+          done
